---
openapi: 3.0.1
info:
  title: ShipShop API V1
  description: Documentation for online groceries shopping engine API
  version: v1
paths:
  "/api/v1/locations":
    get:
      summary: Location index
      tags:
      - Location
      description: "\n"
      responses:
        '200':
          description: Location Index
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/location"
    post:
      summary: Creates a location
      tags:
      - Location
      description: "\n"
      parameters: []
      responses:
        '201':
          description: Location Created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/location"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/new_location"
  "/api/v1/products":
    post:
      summary: Creates a product
      tags:
      - Product
      description: "\n"
      parameters: []
      responses:
        '201':
          description: Stock levels created
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/new_product"
  "/api/v1/locations/{location_id}/stock":
    post:
      summary: Creates inventory in a location
      tags:
      - Stock
      description: |
        This endpoint allows for the replenishing of stock for a specific set of products.

        If no location_id is provided, your default Location will be used to add the provided stock amounts.

        For convenience it creates products that have not been registered based on the product SKU. If a product has
        already been registered with the SKU provided, other attributes for the product will be ignored and the product
        object will not be updated, only the stock quantities for the given location
      parameters:
      - name: location_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: Stock levels created
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                products:
                  type: array
                  items:
                    "$ref": "#/components/schemas/product"
servers:
- url: http://localhost:3000
  description: Local Server
tags:
- name: Location
  description: 'Representation of a location holding inventory (Stock)

'
- name: Stock
  description: 'Location Stock

'
- name: Product
  description: 'Known Product

'
components:
  schemas:
    product:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Orange
        description:
          type: string
        sku:
          type: string
          example: '12345'
        price:
          type: number
          format: double
          example: 1.5
        quantity:
          type: integer
          format: int64
          example: 5
    new_product:
      type: object
      properties:
        name:
          type: string
          example: Orange
        description:
          type: string
        sku:
          type: string
          example: '12345'
        price:
          type: number
          format: double
          example: 1.5
    location:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: 'Store #1'
        description:
          type: string
          example: My first store
    new_location:
      type: object
      properties:
        name:
          type: string
          example: 'Store #1'
        description:
          type: string
          example: My first store
