---
openapi: 3.0.1
info:
  title: ShipShop API V1
  description: Documentation for online groceries shopping engine API
  version: v1
paths:
  "/api/v1/locations":
    get:
      summary: Location index
      tags:
      - Location
      description: 'List of all created locations

'
      responses:
        '200':
          description: Location Index
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/location"
    post:
      summary: Creates a location
      tags:
      - Location
      description: 'In order to hold inventory, a location must first be created.

'
      parameters: []
      responses:
        '201':
          description: Location Created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/location"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/new_location"
  "/api/v1/products":
    post:
      summary: Registers a product
      tags:
      - Product
      description: |
        This endpoint allows for a bulk registration of products to be sold in your store. An array can be sent in the
        request body with each product's information.

        It is _important_ to note that products are identified by their SKU, therefore if a registered product is found
        with the same SKU, the information passed in the request will be ignored for that particular product.

        Please refer to the UpdateProduct endpoint in order to modify an existing product's information
      parameters: []
      responses:
        '201':
          description: Product Registration
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/new_product"
  "/api/v1/locations/{location_id}/stock":
    post:
      summary: Creates inventory in a location
      tags:
      - Stock
      description: |
        This endpoint allows for the replenishing of stock in a given location for a specific set of products.

        Requires the creation of a location and registration of products
      parameters:
      - name: location_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: Stock levels created
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                products:
                  type: array
                  items:
                    "$ref": "#/components/schemas/product"
servers:
- url: http://localhost:3000
  description: Local Server
tags:
- name: Location
  description: 'Representation of a location holding inventory (Stock)

'
- name: Product
  description: 'Known Product

'
- name: Stock
  description: 'Location Stock

'
components:
  schemas:
    product:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Orange
        description:
          type: string
        sku:
          type: string
          example: '12345'
        price:
          type: number
          format: double
          example: 1.5
        quantity:
          type: integer
          format: int64
          example: 5
    new_product:
      type: object
      properties:
        name:
          type: string
          example: Orange
        description:
          type: string
        sku:
          type: string
          example: '12345'
        price:
          type: number
          format: double
          example: 1.5
    location:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: 'Store #1'
        description:
          type: string
          example: My first store
    new_location:
      type: object
      properties:
        name:
          type: string
          example: 'Store #1'
        description:
          type: string
          example: My first store
